<!DOCTYPE html>
<html lang="tr">
<head>
    <title>Saint Framework Index Page</title>
    <meta charset="utf-8">
    <link href="/css/bootstrap.css" media="screen" rel="stylesheet" />
    <style type="text/css">
        html,
        body{
            height: 100%;
        }
        #push,
        #footer {
            height: 60px;
        }
        #footer {
            position: relative;
            background-color: #f5f5f5;
        }
        #wrap {
            min-height: 100%;
            height: auto !important;
            height: 100%;
            margin-top: 100px;
            /* Negative indent footer by it's height */
            margin: 0 auto -60px;
        }
        .navbar-wrapper {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            z-index: 10;
            margin-top: 20px;
            margin-bottom: -90px;
        }
        .carouselImg {
            top: 0;
            left: 0;
            min-width: 100%;
            height: 300px;
        }
        @media (max-width: 979px) {
            .carouselImg {
                height: 220px;
            }
        }
        @media (max-width: 767px) {
            #footer {
                margin-left: -20px;
                margin-right: -20px;
                padding-left: 20px;
                padding-right: 20px;
            }
            .carouselImg {
                height: 180px;
            }
        }
        .container .credit {
            margin: 20px 0;
        }
    </style>
</head>
<body>
<header id='header'>
    <nav class="navbar-wrapper ">
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-inner">
                    <a class="brand" href="#"> Aziz DURMAZ </a>
                    <div class="pull-right">
                        <ul class="nav">
                            <li><a href="/"><i class="icon-home"></i> Home</a></li>
                            <li class="dropdown">
                                <a href="/blog" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-pencil"></i> Blog</a>
                                <ul class="dropdown-menu">
                                    <li><a href="/blog/dependecyInjection">Aziz</a></li>
                                    <li class="last"><a href="/blog/dependecyInjection">Dependecy Injection</a></li>
                                </ul>
                            </li>
                            <li><a href="/download"><i class="icon-download"></i> Download</a></li>
                            <li  class="active"><a href="/game"><i class="icon-screenshot"></i> Game</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>
<section id="wrap">
    <img src="/img/italy.jpg" alt="" class="carouselImg">
    <div class="container">
        <br />
        <ul class="breadcrumb">
            <li><a href="/"> Home</a><span class="divider"></span></li>
            <li>/<span class="divider"></span></li>
            <li><a href="/game">Games</a><span class="divider"></span></li>
            <li>/<span class="divider"></span></li>
            <li class="active">Add Recipie<span class="divider"></span></li>
        </ul>
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span9" id="Game">
                    <div class="page-header">
                        <h1>Oyun</h1>
                    </div>

                    <div class="span9" id="Message"></div>
                    <div class="span9"><br /><hr/></div>
                    <div class="span3"><input class="input-small" type="text" id="firstElement" value="" placeholder=":Element 1..."></div>
                    <div class="span3"><input class="input-small" type="text" id="secondElement" value="" placeholder=":Element 2..."></div>
                    <div class="span3"><input class="input-small" type="text" id="newElement" value="" placeholder=":New Element..."></div>
                    <div class="span9"><br /></div>
                    <div class="span3 offset3"><button class="btn btn-info btn-large" id="add">Ekle...</button></div><div class="span3"></div>
                    <div class="span9"><br /><hr/></div>
                    <div class="span9">
                        <br />
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>1. Element</th>
                                    <th>2. Element</th>
                                    <th>Sonuç Elementi</th>
                                </tr>
                            </thead>
                            <tbody id="ingredientList">
                            <?php
                            $i=0;
                            foreach ($recipieList AS $recipie) {
                                $i++;
                            ?>
                                <tr>
                                    <td><?= $i ?></td>
                                    <td><?= @$recipie['search'][0] ?></td>
                                    <td><?= @$recipie['search'][1] ?></td>
                                    <td><?= $recipie['result'] ?></td>
                                </tr>
                            <?php
                            }
                            ?>
                            </tbody>
                        </table>
                        <input type="hidden" id='number' value="<?= $i ?>">
                    </div>
                </div>
                <div class="span3">
                    <div class="page-header">
                        <h3>Heyoo</h3>
                        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean a leo nec justo convallis malesuada ut sit amet nisi. Vestibulum nulla dui, lacinia et mollis ac, porttitor sed tellus.
                            Vestibulum vel lorem ac odio viverra eleifend. Vivamus ac fermentum enim. Phasellus sapien massa, pulvinar non scelerisque non, commodo et erat. Phasellus lacinia erat lacinia nibh mollis scelerisque.
                            Phasellus mauris dolor, suscipit id tincidunt ultrices, pharetra vel quam.</p>
                    </div>
                </div>
            </div>
        </div>
        <div id="push"></div>
    </div>
</section>

<footer id="footer">
    <div class="container">
        <p class="muted credit">St.Nonstop : Aziz DURMAZ (Software Development Supervisor - GittiGidiyor Ebay)<span class="pull-right">2012</span></p>
    </div>
</footer>

<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/bootstrap.js"></script>
<script>
    $(document).ready(function(){
        $("#add").click(function(){
            var firstElement = '', secondElement = '', newElement = '';

            firstElement = $("#firstElement").val();
            secondElement = $("#secondElement").val();
            newElement = $("#newElement").val();
            $.ajax({
                type:"POST",
                data:{element1:firstElement, element2:secondElement, newElement:newElement},
                dataType:"json",
                url:"/game/addajax",
                success:function(data) {
                    $("#Message").html('');
                    if(data.success){
                        $("#ingredientList").append('<tr><td></td><td>'+data.element1+'</td><td>'+data.element2+'</td><td>'+data.newElement+'</td></tr>');
                        $("#Message").append('<div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><strong>Tebrikler!</strong> Artık eklediğiniz '+data.element1+' ve '+data.element2+' elementlerinden <strong>'+data.newElement+'</strong> elde ediliyor.</div>');
                    } else {
                        if(data.existElement != '') {
                            $("#Message").append('<div class="alert alert-fail"><a class="close" data-dismiss="alert">×</a><strong>Uyarı!</strong> Eklediğiniz '+data.element1+' ve '+data.element2+' elementlerinden '+data.existElement+' elde ediliyor. </div>');
                        } else {
                            $("#Message").append('<div class="alert alert-fail"><a class="close" data-dismiss="alert">×</a><strong>Warning!</strong> Hata oluştu</div>');
                        }
                    }
                }
            })
        })
    });
</script>
</body>
</html>